### ISSUE TITLE
onModelChanged is not being called when an item is selected

### ISSUE THREAD

**Issue by prgwar** [marcosflorencio/angular-materializecss-autocomplete#8]
I have defined a element like below 
`<auto-complete  onModelChanged="getItem" model="searchResponse" func="getProducts" property="ProductName" label="Location">`

and getItem(data) function in controller in a scope variable 
but that method is not being called when item is selected from dropdown. when I debugged the  autocomplete  js scope.onModelChanged is undefined even though i have assigned a method, please help me with the issue
<img width="932" alt="screen shot 2017-02-13 at 12 19 01 pm" src="https://cloud.githubusercontent.com/assets/11192559/22873516/a6e90c02-f1e6-11e6-8f3e-66b83f773a9d.png">

**Comment by wwwflorencio** [comment]
Hi @prgwar,
try this:

```html
<auto-complete on-model-changed="getItem" model="searchResponse" func="getProducts" property="ProductName" label="Location">

```
or

```html
<auto-complete on-select="getItem" model="searchResponse" func="getProducts" property="ProductName" label="Location">

```

_["AngularJS normalizes an element's tag and attribute name to determine which elements match which directives. We typically refer to directives by their case-sensitive camelCase normalized name (e.g. ngModel). However, since HTML is case-insensitive, we refer to directives in the DOM by lower-case forms, typically using dash-delimited attributes on DOM elements (e.g. ng-model)."](https://docs.angularjs.org/guide/directive/#normalization)_
